name: translation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_bloc: ^8.0.1
  translator: ^0.1.7
  provider: ^6.0.3
  hive: ^2.2.2
  hive_generator: ^1.1.3
  path_provider: ^2.0.11
  uuid: ^3.0.6
  keyboard_actions: ^4.0.1
  uni_links: ^0.5.1
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  
  plugin_platform_interface: ^2.1.2
  path_provider_platform_interface: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

